services:
  - type: web
    name: message-bot
    runtime: python
    repo: https://github.com/твой-username/твой-репозиторий
    plan: free
    region: frankfurt
    branch: main
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: message-bot-db
          property: connectionString
      - key: APP_URL
        value: https://message-bot.onrender.com
      - key: PORT
        value: 8080

databases:
  - name: message-bot-db
    plan: free
    region: frankfurt
    databaseName: messagebot
    ipAllowList: []